# Generated by Django 5.0.6 on 2024-08-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnekText', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='interviewer',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
