# Generated by Django 5.0.6 on 2024-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatbot_delete_author_alter_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('authors', models.ManyToManyField(related_name='books', to='api.chatbot')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
