# Generated by Django 5.0.6 on 2024-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assingment_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingment',
            name='authors',
            field=models.ManyToManyField(related_name='bots', to='api.chatbot'),
        ),
    ]
