# Generated by Django 5.0.6 on 2024-08-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_assingment_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='authors',
            new_name='bots',
        ),
    ]
