# Generated by Django 5.0.6 on 2024-09-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
