# Generated by Django 5.0.6 on 2024-09-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_assignment_bots_assignment_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('tone', models.CharField(max_length=100)),
                ('condition_name', models.CharField(max_length=100)),
                ('condition_description', models.TextField(max_length=300)),
                ('condition_duration', models.CharField(max_length=100)),
                ('personality_overall', models.TextField(max_length=300)),
                ('personality_type', models.CharField(max_length=100)),
                ('outlook', models.CharField(max_length=100)),
                ('decision_style', models.CharField(max_length=100)),
                ('comm_style', models.CharField(max_length=100)),
                ('life_early', models.TextField(max_length=300)),
                ('life_key_events', models.TextField(max_length=300)),
                ('life_current', models.TextField(max_length=300)),
                ('family', models.TextField(max_length=300)),
                ('friends', models.TextField(max_length=300)),
                ('social_life', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatBot',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 0, 36, 20, 853267)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 0, 36, 20, 853267)),
        ),
    ]
