# Generated by Django 5.0.6 on 2024-10-03 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_title_assignment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
