# Generated by Django 5.0.6 on 2024-10-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='time_limit',
        ),
    ]
