# Generated by Django 5.0.6 on 2024-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='comm_style',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='condition_description',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='condition_duration',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='condition_name',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='decision_style',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='family',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='life_current',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='life_early',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='life_key_events',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='outlook',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='personality_overall',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='personality_type',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='social_life',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='tone',
        ),
        migrations.AddField(
            model_name='personas',
            name='prompt',
            field=models.TextField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
