# Generated by Django 5.0.6 on 2024-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_personas_age_remove_personas_comm_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='byUser',
            field=models.BooleanField(default=True),
        ),
    ]
